In [18]:
import random
import numpy as np
import torch
from torchnet.dataset import TransformDataset, ListDataset
from torchnet.transform import compose

In [38]:
def random_plus(x):
    print("I worked")
    return x + random.randint(1, 2)

In [39]:
transforms = compose([random_plus])

In [40]:
ds = TransformDataset(ListDataset([1, 2, 3]), transforms)

In [41]:
for i in range(2):
    print("="*5)
    for j in ds:
        print(j)

=====
I worked
2
I worked
4
I worked
4
=====
I worked
3
I worked
4
I worked
5


In [42]:
class Sampler:
    def __init__(self):
        self.n_classes = 3
        self.n_way = 3
        self.n_episodes = 2

    def __len__(self):
        return self.n_episodes

    def __iter__(self):
        for i in range(self.n_episodes):
            yield np.random.permutation(self.n_classes)[:self.n_way]


In [43]:
dl = torch.utils.data.DataLoader(ds, batch_sampler=Sampler(), num_workers=0)

In [44]:
for i in range(2):
    print("="*5)
    for j in dl:
        print(j)

=====
I worked
I worked
I worked
tensor([3, 2, 4])
I worked
I worked
I worked
tensor([2, 5, 3])
=====
I worked
I worked
I worked
tensor([3, 5, 4])
I worked
I worked
I worked
tensor([3, 3, 4])
